/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import SQL.Cuenta;
import Utilidades.DecimalDocumentFilter;
import Utilidades.SoloLetrasDocumentFilter;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import Utilidades.LongitudDocumentFilter;
import Utilidades.ValidadorCampos;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;
import java.text.DecimalFormat;
/**
 *
 * @author Lenovo
 */
public class frmCuentas extends javax.swing.JDialog {

    /**
     * Creates new form frmCuentas
     */

    private int idCuentaEnEdicion = 0; // 0 significa modo creación, >0 significa modo edición
    private Cuenta cuentaActual; // Para almacenar la cuenta que se está editando

    public frmCuentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ((AbstractDocument) this.txtCapital.getDocument()).setDocumentFilter(new DecimalDocumentFilter(10,2));
        ((AbstractDocument) this.txtNombre.getDocument()).setDocumentFilter(new SoloLetrasDocumentFilter(20));
        ((AbstractDocument) this.txtApellidoPaterno.getDocument()).setDocumentFilter(new SoloLetrasDocumentFilter(20));
        ((AbstractDocument) this.txtApellidoMaterno.getDocument()).setDocumentFilter(new SoloLetrasDocumentFilter(20));
        ((AbstractDocument) this.txtCorreo.getDocument()).setDocumentFilter(new LongitudDocumentFilter(100));

        setLocationRelativeTo(null); // Centra la ventana
        limpiarCampos(); // Inicializa el formulario en modo creación
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtCapital = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblIdCuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cuentas de ahorro");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido Paterno");

        jLabel4.setText("Apellido Materno");

        jLabel5.setText("Capital");

        jLabel6.setText("Correo");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPaternoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblIdCuenta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCorreo)
                    .addComponent(txtCapital)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtApellidoPaterno)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblIdCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIdCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPaternoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Validaciones básicas de campos
        if (txtNombre.getText().trim().isEmpty() || txtApellidoPaterno.getText().trim().isEmpty() ||
            txtCapital.getText().trim().isEmpty() || txtCorreo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios (Nombre, Apellido Paterno, Capital, Correo).", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validación de correo usando tu clase ValidadorCampos
        if(!ValidadorCampos.esEmailValido(this.txtCorreo.getText().trim())){
            JOptionPane.showMessageDialog(this, "Correo inválido. Por favor, ingrese un correo válido.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
            this.txtCorreo.requestFocus();
            this.txtCorreo.selectAll();
            return;
        }

        double capital;
        try {
            capital = Double.parseDouble(txtCapital.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El capital debe ser un número válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Cuenta cuentaAProcesar;
        if (idCuentaEnEdicion > 0) { // Estamos en modo edición
            cuentaAProcesar = this.cuentaActual; // Usamos el objeto que ya cargamos para edición
            cuentaAProcesar.setIdCuenta(idCuentaEnEdicion); // Nos aseguramos de que el ID esté seteado
        } else { // Estamos en modo creación
            cuentaAProcesar = new Cuenta();
        }

        // Asignar los valores de los campos de la UI al objeto Cuenta
        cuentaAProcesar.setNombre(txtNombre.getText().trim());
        cuentaAProcesar.setApellidoPaterno(txtApellidoPaterno.getText().trim());
        cuentaAProcesar.setApellidoMaterno(txtApellidoMaterno.getText().trim()); // Puede ser vacío
        cuentaAProcesar.setCapital(capital);
        cuentaAProcesar.setCorreo(txtCorreo.getText().trim());

        boolean operacionExitosa;
        if (idCuentaEnEdicion > 0) { // Es una actualización (editar)
            operacionExitosa = cuentaAProcesar.actualizar();
            if (operacionExitosa) {
                JOptionPane.showMessageDialog(this, "Cuenta actualizada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar la cuenta.", "Error de Actualización", JOptionPane.ERROR_MESSAGE);
            }
        } else { // Es una inserción (crear)
            operacionExitosa = cuentaAProcesar.insertar();
            if (operacionExitosa) {
                JOptionPane.showMessageDialog(this, "Cuenta creada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos(); // Opcional: limpiar campos para otra inserción
            } else {
                JOptionPane.showMessageDialog(this, "Error al crear la cuenta.", "Error de Inserción", JOptionPane.ERROR_MESSAGE);
            }
        }

        if (operacionExitosa) {
            this.dispose(); // Cierra el formulario si la operación fue exitosa
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
         this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

      private void limpiarCampos() {
        if (lblIdCuenta != null) { // Asegúrate de que lblIdCuenta exista
            lblIdCuenta.setText("ID: Nuevo Registro");
        }
        txtNombre.setText("");
        txtApellidoPaterno.setText("");
        txtApellidoMaterno.setText("");
        txtCapital.setText("");
        txtCorreo.setText("");
        // Si tienes un JDateChooser para la fecha de registro:
        // if (dateChooserFechaRegistro != null) {
        //     dateChooserFechaRegistro.setDate(null);
        // }
        idCuentaEnEdicion = 0; // Restablecer a 0 para indicar modo creación
        btnGuardar.setText("Guardar"); // Cambiar el texto del botón a "Guardar"
        this.setTitle("Crear Nueva Cuenta"); // Cambiar el título de la ventana
    }

    // *** NUEVO MÉTODO: Carga los datos de una cuenta existente para edición ***
    public void cargarDatosCuentaParaEdicion(Cuenta cuenta) {
       this.cuentaActual = cuenta;
        this.idCuentaEnEdicion = cuenta.getIdCuenta();

        if (lblIdCuenta != null) {
            lblIdCuenta.setText("ID: " + cuenta.getIdCuenta());
        }
        txtNombre.setText(cuenta.getNombre());
        txtApellidoPaterno.setText(cuenta.getApellidoPaterno());
        txtApellidoMaterno.setText(cuenta.getApellidoMaterno());

        // Formatear el capital para evitar notación científica
        DecimalFormat df = new DecimalFormat("#.00");
        String capitalFormateado;
        if (cuenta.getCapital() == Math.floor(cuenta.getCapital())) {
            capitalFormateado = String.format("%.0f", cuenta.getCapital());
        } else {
            capitalFormateado = df.format(cuenta.getCapital());
        }

        txtCapital.setText(capitalFormateado);

        // *** ¡NUEVA LÍNEA AQUÍ para hacerlo de solo lectura! ***
        txtCapital.setEditable(false); 
        // ******************************************************

        txtCorreo.setText(cuenta.getCorreo());

        // ... (resto del código para JDateChooser si lo tienes) ...

        btnGuardar.setText("Actualizar");
        this.setTitle("Editar Cuenta - ID: " + cuenta.getIdCuenta());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCuentas dialog = new frmCuentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblIdCuenta;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCapital;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
